Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.synced_folder "../client/dist", "/var/www"
  config.vm.synced_folder "../wp-sexy-rest", "/home/vagrant/wp-sexy-rest"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get -y update
    sudo apt-get -y install apache2
    echo mysql-server mysql-server/root_password password password | sudo debconf-set-selections
    echo mysql-server mysql-server/root_password_again password password | sudo debconf-set-selections
    sudo apt-get -y install mysql-server libapache2-mod-auth-mysql php5-mysql
    sudo mysql_install_db
    mysqladmin create wordpress -uroot -ppassword
    sudo apt-get -y install php5 libapache2-mod-php5 php5-mcrypt
    sudo apt-get -y install curl
    curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    sudo chmod +x wp-cli.phar
    sudo mv wp-cli.phar /usr/local/bin/wp
    sudo -u vagrant -i -- wp core download --path=/home/vagrant/wordpress
    sudo -u vagrant -i -- wp core config --dbname=wordpress --dbuser=root --dbpass=password --path=/home/vagrant/wordpress
    sudo -u vagrant -i -- wp core install --url=http://localhost/wordpress --title=ember-wp-green --admin_user=admin --admin_password=password --admin_email=noreply@gmail.com --path=/home/vagrant/wordpress
    sudo -u vagrant -i -- wp plugin install json-rest-api --path=/home/vagrant/wordpress
    sudo -u vagrant -i -- wp plugin activate json-rest-api --path=/home/vagrant/wordpress
    sudo rm /etc/apache2/sites-enabled/000-default
    sudo cp /vagrant/000-default /etc/apache2/sites-enabled/000-default
    sudo cp /vagrant/.htaccess /home/vagrant/wordpress/.htaccess
    sudo -u vagrant -i -- wp plugin install wordpress-importer --activate --path=/home/vagrant/wordpress
    sudo -u vagrant -i -- wp import /vagrant/wp-test-data.xml --path=/home/vagrant/wordpress --authors=create
    sudo curl -sS https://getcomposer.org/installer | php
    sudo mv composer.phar /usr/local/bin/composer
    cd /home/vagrant/wp-sexy-rest
    /usr/local/bin/composer install
    ln -s /home/vagrant/wp-sexy-rest /home/vagrant/wordpress/wp-content/plugins/wp-sexy-rest
    sudo -u vagrant -i -- wp plugin activate wp-sexy-rest --path=/home/vagrant/wordpress
    sudo -u vagrant -i -- wp rewrite structure '/%postname%/' --path=/home/vagrant/wordpress
    sudo a2enmod rewrite
    sudo service apache2 restart
  SHELL

  config.vm.network "forwarded_port", guest: 80, host: 80
end
